version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - 9900:80
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
    - "host.docker.internal:host-gateway"
