version: '3.1'

services:
  api:
    image: ivanyeoh/converter-api
    restart: always
    ports:
      - 5990-5992:5990

  web:
    image: ivanyeoh/converter-web
    restart: always
    ports:
      - 3990-3992:3990
