name: Converter WEB Auto Deployment

on:
  push:
    branches: ["main"]
    paths:
      - apps/web/**
      - packages/shared-helpers/**
      - .github/workflows/deploy-web*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create .env 🤫
        uses: DeveloperRic/action-create-env@v1.0.4
        with:
          full_text: |
            NEXT_PUBLIC_HOST=https://converter.testrun.work
          directory: ./apps/web/
          include_env_vars: false
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          dockerfile: ./apps/web/Dockerfile
          name: ivanyeoh/converter-web
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          snapshot: true

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy & restart
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: converter.testrun.work
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            mkdir -p /root/converter
            cd /root/converter
            [ -f docker-compose-prod.yml ] && mv docker-compose-prod.yml docker-compose.yml
            docker compose pull web
            docker compose up web -d
